// © 2026 Graysbrook Ltd. Proprietary — all rights reserved. See LICENSE.
// Medicus Suite — Phrases SHIPPED PACK (curated practice-tier blocks)
//
// ┌─────────────────────────────────────────────────────────────────────────┐
// │ CONTENT DROP-IN POINT.                                                  │
// │ SHIPPED_PACK below is the curated v2 pack (59 blocks, authored to NHS   │
// │ reading-age 9–11 for patient-audience blocks; safety-net blocks follow  │
// │ the BJGP pattern; wording pending CSO sign-off — see H-052). All future │
// │ content updates replace SHIPPED_PACK in THIS ONE FILE.                  │
// │                                                                         │
// │ Rules for the drop-in:                                                  │
// │  1. Keep the shape: { version: <int>, categories: [{id,label}],         │
// │     blocks: [ ... ] } with the exact block schema documented in         │
// │     shared/phrases-core.js.                                             │
// │  2. BUMP `version` (integer) whenever blocks are ADDED — it gates       │
// │     PhrasesCore.mergeShippedPack, and without the bump existing         │
// │     installs never receive the new blocks (the stranded-defaults        │
// │     failure class — see CLAUDE.md on defaults.json's version).          │
// │     Changed bodies on an EXISTING id do NOT propagate to installs that  │
// │     already carry that id (the user's stored block wins) — prefer a new │
// │     id + noting the old one for tombstone-aware review.                 │
// │  3. Every block must pass PhrasesCore.validateBlock and use a category  │
// │     id from `categories` — test-phrases-core.js validates the whole     │
// │     pack in CI, so a malformed drop-in fails the build, not a user.     │
// └─────────────────────────────────────────────────────────────────────────┘
//
// Dual-mode export (window.PhrasesPresets / require) — same pattern as
// shared/phrases-core.js. This file deliberately has NO dependency on
// phrases-core: mergeShippedPack takes the pack as an argument, so load order
// between the two classic scripts never matters.

'use strict';

(function (global) {
  function deepFreeze(o) {
    if (o && typeof o === 'object' && !Object.isFrozen(o)) {
      Object.freeze(o);
      for (const k of Object.keys(o)) deepFreeze(o[k]);
    }
    return o;
  }

  // Curated pack v2 — authored to NHS reading-age 9-11 (patient-audience
  // blocks), BJGP-pattern safety-nets (specific alarm features + concrete
  // timeframe + named route + catch-all), *** = manual-fill placeholder the
  // clinician must type over. Version 2 supersedes the v1 build placeholder
  // so the merge reaches installs that saved a config against it.
  const SHIPPED_PACK = deepFreeze({
    version: 2,
    categories: [
      {
        id: 'openers',
        label: 'Openers',
      },
      {
        id: 'results-normal',
        label: 'Results — normal',
      },
      {
        id: 'results-borderline',
        label: 'Results — borderline',
      },
      {
        id: 'conditions',
        label: 'Condition explainers',
      },
      {
        id: 'safety-netting',
        label: 'Safety-netting',
      },
      {
        id: 'needs-call',
        label: 'Needs a call',
      },
      {
        id: 'admin',
        label: 'Admin',
      },
      {
        id: 'sign-offs',
        label: 'Sign-offs',
      },
    ],
    blocks: [
      {
        id: 'open-pain',
        title: 'Opener — ongoing pain',
        body: "I'm sorry to hear you've been struggling with pain from ***. That's not an easy thing to live with, and I want to help.",
        trigger: 'openpain',
        keywords: 'pain opener sorry ongoing chronic empathy acknowledgement',
        category: 'openers',
        audience: 'patient',
        leafletUrl: '',
        slot: 'opener',
      },
      {
        id: 'open-mentalhealth',
        title: 'Opener — mental health struggle',
        body: "Thank you for telling me how you've been feeling. It isn't always easy to reach out, and I'm glad you did.",
        trigger: 'openmh',
        keywords: 'mental health opener low mood anxiety depression struggling empathy',
        category: 'openers',
        audience: 'patient',
        leafletUrl: '',
        slot: 'opener',
      },
      {
        id: 'open-worried-result',
        title: 'Opener — worried about a result',
        body: "I understand waiting to hear about a result can be an anxious time. Thank you for your patience while we've been looking into this.",
        trigger: 'openworry',
        keywords: 'worried result opener anxious waiting test anxiety',
        category: 'openers',
        audience: 'patient',
        leafletUrl: '',
        slot: 'opener',
      },
      {
        id: 'open-frustrated-waiting',
        title: 'Opener — frustrated with a delay',
        body: "I'm sorry for the delay with ***. I know that's frustrating. Thank you for bearing with us.",
        trigger: 'openwait',
        keywords: 'frustrated delay waiting opener apology sorry',
        category: 'openers',
        audience: 'patient',
        leafletUrl: '',
        slot: 'opener',
      },
      {
        id: 'open-bereavement',
        title: 'Opener — bereavement',
        body: 'I was very sorry to hear about the loss of ***. My condolences to you and your family.',
        trigger: 'openbereave',
        keywords: 'bereavement condolences loss death opener sympathy sorry for your loss',
        category: 'openers',
        audience: 'patient',
        leafletUrl: '',
        slot: 'opener',
      },
      {
        id: 'open-general',
        title: 'Opener — general acknowledgement',
        body: 'Thank you for getting in touch.',
        trigger: 'opengen',
        keywords: 'general opener thank you getting in touch neutral',
        category: 'openers',
        audience: 'patient',
        leafletUrl: '',
        slot: 'opener',
      },
      {
        id: 'norm-fbc',
        title: 'Normal result — full blood count (FBC)',
        body: "Your full blood count (a blood test that checks for anaemia, infection and other blood conditions) has come back normal. This means there's no sign of any of the problems this test looks for. No action is needed based on this result alone. As always, do get in touch if your symptoms continue or change.",
        trigger: 'normfbc',
        keywords: 'fbc full blood count blood test normal haemoglobin anaemia',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-ue',
        title: 'Normal result — kidney function (U&E)',
        body: 'Your kidney function test (U&E) has come back normal, showing your kidneys are working well and your salt levels are balanced. No action is needed based on this result. If you were having this test because of specific symptoms, please let us know if they continue.',
        trigger: 'normue',
        keywords: 'kidney function ue urea electrolytes normal renal',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-lft',
        title: 'Normal result — liver function test (LFT)',
        body: "Your liver function test has come back normal. This means there's no sign of your liver being under strain or inflamed. No action is needed based on this result alone. If you have any ongoing symptoms, please let us know.",
        trigger: 'normlft',
        keywords: 'liver function test lft normal liver enzymes',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-tft',
        title: 'Normal result — thyroid function test (TFT)',
        body: 'Your thyroid function test has come back normal, meaning your thyroid (the gland in your neck that helps control your metabolism) is working as it should. No action is needed based on this result. If your symptoms continue, please get back in touch.',
        trigger: 'normtft',
        keywords: 'thyroid function test tft normal underactive overactive',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-hba1c',
        title: 'Normal result — HbA1c (blood sugar)',
        body: "Your HbA1c (average blood sugar over three months) is normal. There's no sign of diabetes or pre-diabetes. No action is needed. It's still good to eat well and stay active.",
        trigger: 'normhba1c',
        keywords: 'hba1c blood sugar diabetes normal glucose',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-lipids',
        title: 'Normal result — cholesterol (lipids)',
        body: 'Your cholesterol (lipid) test has come back within the normal range. This means your risk from cholesterol alone is low at the moment. No action is needed based on this result. Keeping active and eating well will help keep it that way.',
        trigger: 'normlipid',
        keywords: 'cholesterol lipids lipid profile normal heart',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-vitd',
        title: 'Normal result — vitamin D',
        body: 'Your vitamin D level has come back normal. Vitamin D helps keep your bones and muscles healthy. No supplements or action are needed based on this result.',
        trigger: 'normvitd',
        keywords: 'vitamin d normal bones muscles',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-b12',
        title: 'Normal result — vitamin B12 and folate',
        body: 'Your vitamin B12 and folate levels have come back normal. These vitamins are important for making healthy blood cells and for your nerves. No action or supplements are needed based on this result.',
        trigger: 'normb12',
        keywords: 'vitamin b12 folate normal anaemia nerves',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-psa',
        title: 'Normal result — PSA (prostate)',
        body: "Your PSA (prostate blood test) is within the normal range for your age. This test isn't perfect. It can miss a problem, or flag one that isn't there. Please come back if you get any urinary symptoms, such as difficulty passing urine, or if you have any other concerns.",
        trigger: 'normpsa',
        keywords: 'psa prostate specific antigen normal prostate',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-urine',
        title: 'Normal result — urine test',
        body: 'Your urine test has come back normal, with no sign of infection, blood, or protein. No action is needed based on this result. If your symptoms continue, please get back in touch.',
        trigger: 'normurine',
        keywords: 'urine test normal infection blood protein dipstick',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-bp',
        title: 'Normal result — blood pressure reading',
        body: "Your blood pressure reading of ***/*** was within the normal range. No action is needed based on this reading alone. It's still worth having your blood pressure checked from time to time, as recommended.",
        trigger: 'normbp',
        keywords: 'blood pressure reading normal bp hypertension',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'norm-cxr',
        title: 'Normal result — chest X-ray',
        body: 'Your chest X-ray has come back clear, with no sign of infection or other concerning changes. No action is needed based on this result. If your symptoms continue or you develop new ones such as breathlessness, please get back in touch.',
        trigger: 'normcxr',
        keywords: 'chest x-ray xray normal clear lungs',
        category: 'results-normal',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'bord-hba1c',
        title: 'Borderline result — HbA1c (pre-diabetes range)',
        body: "Your HbA1c blood sugar result is slightly above the normal range. This is called 'pre-diabetes'. It is not diabetes, and it's not an emergency. It's a useful early warning sign. The next step is to look at your diet and activity, and repeat the test in *** months.",
        trigger: 'bordhba1c',
        keywords: 'hba1c borderline prediabetes pre-diabetes raised blood sugar',
        category: 'results-borderline',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'bord-lft',
        title: 'Borderline result — mildly raised liver enzymes',
        body: "Your liver test shows a small rise in one or two liver enzymes. This is common. It's often linked to things like alcohol, weight, or certain medicines, rather than anything serious. It's not an emergency. We'd suggest repeating the test in *** weeks to see if it settles.",
        trigger: 'bordlft',
        keywords: 'liver function borderline mildly raised enzymes lft',
        category: 'results-borderline',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'bord-lipids',
        title: 'Borderline result — mildly raised cholesterol',
        body: "Your cholesterol result is a little above the ideal range. This is not an emergency. It doesn't mean you have heart disease. The usual next step is to look at your diet, activity, and other risk factors. We may repeat the test in *** months.",
        trigger: 'bordlipid',
        keywords: 'cholesterol borderline slightly raised lipids',
        category: 'results-borderline',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'bord-vitd',
        title: 'Borderline result — mildly low vitamin D',
        body: 'Your vitamin D level is a little below the ideal range. This is very common in the UK. It is not an emergency. The usual next step is a course of vitamin D tablets, which you can buy over the counter, for around *** months.',
        trigger: 'bordvitd',
        keywords: 'vitamin d borderline low mildly deficient',
        category: 'results-borderline',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'bord-tsh',
        title: 'Borderline result — thyroid (TSH)',
        body: "Your thyroid test (TSH) is slightly outside the normal range. This doesn't always mean there's a problem with your thyroid. It's not an emergency. We'd suggest repeating the test in *** weeks to see if it settles, or needs a further look.",
        trigger: 'bordtsh',
        keywords: 'thyroid tsh borderline slightly abnormal',
        category: 'results-borderline',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'bord-bp',
        title: 'Borderline result — mildly raised blood pressure',
        body: "Your blood pressure reading of ***/*** is a little higher than ideal. One reading like this doesn't mean you have high blood pressure. It's not an emergency. We'll usually check it again over *** weeks, at home or with us, to see the pattern.",
        trigger: 'bordbp',
        keywords: 'blood pressure borderline slightly raised high',
        category: 'results-borderline',
        audience: 'patient',
        leafletUrl: '',
        slot: 'substance',
      },
      {
        id: 'cond-uti',
        title: 'Condition explainer — UTI (urine infection)',
        body: 'A urine infection (UTI) happens when germs get into your bladder or waterworks. It can cause burning when you wee, needing to wee more often, or pain low in your tummy. UTIs are common. They usually clear up well with the right antibiotic and plenty of fluids.',
        trigger: 'conduti',
        keywords: 'uti urine infection cystitis bladder waterworks',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/urinary-tract-infections-utis/',
        slot: 'substance',
      },
      {
        id: 'cond-chest-vs-cold',
        title: 'Condition explainer — chest infection vs a cold',
        body: "A chest infection often causes a cough with phlegm, a fever, and feeling more unwell than a cold. You may also feel breathless. A cold usually stays 'above the neck' — a blocked nose and sore throat — and gets better in a week or two on its own. A chest infection can need closer monitoring, or antibiotics.",
        trigger: 'condchest',
        keywords: 'chest infection cold difference cough bronchitis phlegm',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/chest-infection/',
        slot: 'substance',
      },
      {
        id: 'cond-eczema',
        title: 'Condition explainer — eczema',
        body: 'Eczema is a condition that makes your skin dry, itchy, and sometimes red or cracked. It tends to flare up and settle down over time. The main treatment is regular use of emollients (moisturisers) to protect the skin, with a steroid cream for flare-ups when needed.',
        trigger: 'condeczema',
        keywords: 'eczema dry itchy skin dermatitis flare emollient',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/atopic-eczema/',
        slot: 'substance',
      },
      {
        id: 'cond-migraine',
        title: 'Condition explainer — migraine',
        body: 'A migraine is a type of headache. It often comes with feeling sick, and sensitivity to light or sound. It can last from a few hours to a few days. Resting in a quiet, dark room, drinking enough water, and taking pain relief early can all help.',
        trigger: 'condmigraine',
        keywords: 'migraine headache nausea light sensitivity aura',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/migraine/',
        slot: 'substance',
      },
      {
        id: 'cond-reflux',
        title: 'Condition explainer — reflux (heartburn)',
        body: "Reflux (heartburn) happens when acid from your stomach comes back up your gullet. This causes a burning feeling in your chest. It's often worse after eating or lying down. Smaller meals, avoiding food near bedtime, and antacids can all help.",
        trigger: 'condreflux',
        keywords: 'reflux heartburn acid indigestion gord',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/heartburn-and-acid-reflux/',
        slot: 'substance',
      },
      {
        id: 'cond-anxiety-physical',
        title: 'Condition explainer — anxiety and physical symptoms',
        body: 'Anxiety can cause very real physical symptoms. A racing heart, a tight chest, a churning stomach, or shaking, can all happen even when nothing is wrong in your body. This is because your body has switched on its stress response. Knowing this link is often the first step. Relaxation and, if needed, talking therapy can help too.',
        trigger: 'condanx',
        keywords: 'anxiety physical symptoms racing heart panic palpitations',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/mental-health/conditions/generalised-anxiety-disorder-gad/',
        slot: 'substance',
      },
      {
        id: 'cond-tennis-elbow',
        title: 'Condition explainer — tennis elbow',
        body: "Tennis elbow causes pain on the outside of your elbow. It's usually caused by gripping or twisting a lot — you don't need to play tennis to get it. Resting the arm from what triggers it helps. Gentle stretches and pain relief usually help it settle.",
        trigger: 'condtennis',
        keywords: 'tennis elbow arm pain lateral epicondylitis',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/tennis-elbow/',
        slot: 'substance',
      },
      {
        id: 'cond-plantar-fasciitis',
        title: 'Condition explainer — plantar fasciitis',
        body: "Plantar fasciitis causes pain under your heel, or along the sole of your foot. It's often worst with your first steps in the morning. It usually gets better with rest, supportive shoes, and gentle calf and foot stretches.",
        trigger: 'condplantar',
        keywords: 'plantar fasciitis heel pain foot sole',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/plantar-fasciitis/',
        slot: 'substance',
      },
      {
        id: 'cond-ibs',
        title: 'Condition explainer — IBS',
        body: "IBS (irritable bowel syndrome) is a common gut problem. It can cause tummy pain, bloating, and changes to your bowel habit. This might mean loose poo, harder poo, or both. It's not caused by anything serious. Diet changes can help. Sometimes medicine helps too.",
        trigger: 'condibs',
        keywords: 'ibs irritable bowel syndrome bloating tummy pain diarrhoea constipation',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/irritable-bowel-syndrome-ibs/',
        slot: 'substance',
      },
      {
        id: 'cond-viral-self-care',
        title: 'Condition explainer — viral illness self-care',
        body: "Most coughs, colds, and bugs get better on their own. This usually takes *** days, as your body fights it off. Antibiotics don't work on viruses. Rest, fluids, and simple pain relief are usually all you need.",
        trigger: 'condviral',
        keywords: 'viral illness cold self care rest fluids virus antibiotics',
        category: 'conditions',
        audience: 'patient',
        leafletUrl: 'https://www.nhs.uk/conditions/common-cold/',
        slot: 'substance',
      },
      {
        id: 'sn-chest-infection',
        title: 'Safety-net — adult chest infection',
        body: "Most chest infections settle with rest and fluids. Please contact NHS 111, or book an urgent appointment, if you: become more breathless, still have a fever after *** days, cough up blood, get chest pain, or feel confused or very drowsy. If you're not improving by *** days, please get back in touch — or if you just feel something isn't right.",
        trigger: 'snchest',
        keywords: 'safety net chest infection breathless fever red flags',
        category: 'safety-netting',
        audience: 'patient',
        leafletUrl: '',
        slot: 'safetynet',
      },
      {
        id: 'sn-child-fever',
        title: 'Safety-net — child with fever',
        body: "Most fevers in children settle by themselves. Please take your child to A&E, or call 999, if they: have a stiff neck, have a rash that doesn't fade when you press a glass on it, are hard to wake, are struggling to breathe, or are under *** months old with a temperature above 38°C. If you're worried but it's none of these, call NHS 111 — or if you just feel something isn't right.",
        trigger: 'snchildfever',
        keywords: 'child fever safety net paediatric rash stiff neck 999',
        category: 'safety-netting',
        audience: 'patient',
        leafletUrl: '',
        slot: 'safetynet',
      },
      {
        id: 'sn-uti-antibiotics',
        title: 'Safety-net — UTI treated with antibiotics',
        body: "This course of antibiotics should start to ease your symptoms within *** days. Please contact us, or NHS 111, if: things haven't got better after *** days, you get a fever, you get pain in your back or side, you feel shivery, or you see blood in your wee — or if you just feel something isn't right.",
        trigger: 'snuti',
        keywords: 'uti safety net antibiotics fever back pain worsening',
        category: 'safety-netting',
        audience: 'patient',
        leafletUrl: '',
        slot: 'safetynet',
      },
      {
        id: 'sn-headache',
        title: 'Safety-net — headache',
        body: "Most headaches are not serious. Please go to A&E, or call 999, if you get: a sudden, severe headache unlike any you've had before, a headache with a stiff neck and rash, weakness down one side, confusion, or changes to your vision. If it hasn't settled within *** days, please get back in touch — or if you just feel something isn't right.",
        trigger: 'snheadache',
        keywords: 'headache safety net sudden severe stiff neck vision',
        category: 'safety-netting',
        audience: 'patient',
        leafletUrl: '',
        slot: 'safetynet',
      },
      {
        id: 'sn-abdo-pain',
        title: 'Safety-net — abdominal pain',
        body: "Please go to A&E, or call 999, if: your tummy pain gets bad and constant, you keep being sick and can't keep fluids down, you see blood in your sick or poo, you get a fever with the pain, or your tummy goes hard and very tender to touch. If the pain hasn't settled within *** days, please get back in touch — or if you just feel something isn't right.",
        trigger: 'snabdo',
        keywords: 'abdominal pain tummy safety net vomiting blood fever',
        category: 'safety-netting',
        audience: 'patient',
        leafletUrl: '',
        slot: 'safetynet',
      },
      {
        id: 'sn-low-mood-treatment',
        title: 'Safety-net — low mood, treatment started',
        body: "It can take *** weeks for this treatment to start helping. Things can feel different before they feel better. Please contact us urgently, call NHS 111, or go to A&E, if: you have thoughts of harming yourself or ending your life, you feel unsafe, your mood suddenly gets worse, or you get any new or odd side effects — or if you just feel something isn't right.",
        trigger: 'snlowmood',
        keywords: 'low mood mental health treatment safety net self harm suicide antidepressant',
        category: 'safety-netting',
        audience: 'patient',
        leafletUrl: '',
        slot: 'safetynet',
      },
      {
        id: 'sn-back-pain',
        title: 'Safety-net — back pain',
        body: "Most back pain settles with movement and simple pain relief. Please get urgent care if you notice: numbness around your back passage or private parts, trouble controlling your bladder or bowel, numbness or weakness in both legs, or pain that started after an injury. Call 999 or go to A&E if so. If it hasn't eased in *** weeks, please get back in touch — or if you just feel something isn't right.",
        trigger: 'snback',
        keywords: 'back pain safety net cauda equina numbness bladder',
        category: 'safety-netting',
        audience: 'patient',
        leafletUrl: '',
        slot: 'safetynet',
      },
      {
        id: 'sn-wound-infection',
        title: 'Safety-net — wound or skin infection',
        body: "A healing wound should slowly look better, not worse. Please contact us, or NHS 111, quickly if you notice: redness spreading around the wound, more pus or fluid, a fever, pain that's getting worse rather than easing, or red streaks on the skin nearby — or if you just feel something isn't right.",
        trigger: 'snwound',
        keywords: 'wound skin infection safety net redness discharge pus',
        category: 'safety-netting',
        audience: 'patient',
        leafletUrl: '',
        slot: 'safetynet',
      },
      {
        id: 'call-result-needs-talk',
        title: 'Needs a call — result needs a conversation',
        body: "I've had a look at your recent result, and I'd like to talk it through with you rather than send it as a message. Please could you book a telephone appointment in the next *** days?",
        trigger: 'callres',
        keywords: 'result needs call phone conversation not a message',
        category: 'needs-call',
        audience: 'patient',
        leafletUrl: '',
        slot: 'whole',
      },
      {
        id: 'call-needs-exam',
        title: "Needs a call — I'd like to examine you",
        body: "Based on what you've described, I think it would be best for me to examine you in person. Please could you book an appointment in the next *** days?",
        trigger: 'callexam',
        keywords: 'needs examination in person appointment cannot assess by message',
        category: 'needs-call',
        audience: 'patient',
        leafletUrl: '',
        slot: 'whole',
      },
      {
        id: 'call-too-complex',
        title: 'Needs a call — too complex for messaging',
        body: "What you've raised covers a few things that are difficult to do justice to by message. I'd like to arrange a telephone or in-person appointment so we can go through it properly — please could you book one in the next *** days?",
        trigger: 'calltoocomplex',
        keywords: 'too complex for messaging multiple issues appointment needed',
        category: 'needs-call',
        audience: 'patient',
        leafletUrl: '',
        slot: 'whole',
      },
      {
        id: 'call-urgent-conversation',
        title: 'Needs a call — urgent conversation needed',
        body: "I've looked at what you've sent. I think we need to talk soon, rather than write back. Please contact reception today to arrange a telephone appointment, if you can.",
        trigger: 'callurgent',
        keywords: 'urgent needs call today soon conversation reception',
        category: 'needs-call',
        audience: 'patient',
        leafletUrl: '',
        slot: 'whole',
      },
      {
        id: 'admin-fit-note',
        title: 'Admin — fit note (sick note) process',
        body: "For a fit note (sick note), you can self-certify for the first 7 days of an illness and don't need one from us for that period. After that, please book an appointment (which can often be a telephone one) so we can discuss and arrange this with you.",
        trigger: 'adminfitnote',
        keywords: 'fit note sick note self certify sickness certificate work',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'whole',
      },
      {
        id: 'admin-how-to-book',
        title: 'Admin — how to book an appointment',
        body: "You can book an appointment with us by ***. If it's urgent, please call reception directly.",
        trigger: 'adminbook',
        keywords: 'how to book appointment reception online phone',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'whole',
      },
      {
        id: 'admin-prescription-pharmacy',
        title: 'Admin — prescription ready at pharmacy',
        body: "It usually takes *** working days for a prescription to reach the chemist. Ask the chemist if it's not ready. Let us know if there's any other issue.",
        trigger: 'adminpharmacy',
        keywords: 'prescription ready pharmacy collect electronic nominated',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'whole',
      },
      {
        id: 'admin-medication-review',
        title: 'Admin — medication review due',
        body: "Our records show you're due a medication review. This is a chance to check your current medicines are still right for you. Please book a routine appointment in the next *** weeks so we can go through this together.",
        trigger: 'adminmedreview',
        keywords: 'medication review due medicines check repeat prescription',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'whole',
      },
      {
        id: 'admin-send-photo',
        title: 'Admin — please send a photo',
        body: 'It would help to see a photo of ***. Please take it in good light, ideally daylight. Send it through the secure messaging system, with a short note on when it started.',
        trigger: 'adminphoto',
        keywords: 'send a photo picture image skin rash lesion',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'nextstep',
      },
      {
        id: 'next-no-action',
        title: 'Next step — no action needed',
        body: 'No action is needed at this time based on the above.',
        trigger: 'nextnoaction',
        keywords: 'no action needed nothing further reassurance',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'nextstep',
      },
      {
        id: 'next-repeat-test',
        title: 'Next step — repeat the test',
        body: "We'd suggest repeating this test in *** to check things again.",
        trigger: 'nextrepeat',
        keywords: 'repeat test in future recheck follow up',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'nextstep',
      },
      {
        id: 'next-book-routine',
        title: 'Next step — book a routine appointment',
        body: 'The next step would be to book a routine appointment in the next *** so we can discuss this further.',
        trigger: 'nextbookroutine',
        keywords: 'book routine appointment next step face to face',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'nextstep',
      },
      {
        id: 'next-book-call',
        title: 'Next step — book a telephone appointment',
        body: 'The next step would be to book a telephone appointment in the next *** so we can talk this through.',
        trigger: 'nextbookcall',
        keywords: 'book telephone appointment call next step phone',
        category: 'admin',
        audience: 'patient',
        leafletUrl: '',
        slot: 'nextstep',
      },
      {
        id: 'signoff-warm',
        title: 'Sign-off — warm and simple',
        body: 'Best wishes, Dr ***',
        trigger: 'signoffwarm',
        keywords: 'sign off best wishes warm closing',
        category: 'sign-offs',
        audience: 'patient',
        leafletUrl: '',
        slot: 'signoff',
      },
      {
        id: 'signoff-take-care',
        title: 'Sign-off — take care, get in touch',
        body: "Take care, and don't hesitate to get back in touch if you need to. Dr ***",
        trigger: 'signoffcare',
        keywords: 'sign off take care get in touch closing',
        category: 'sign-offs',
        audience: 'patient',
        leafletUrl: '',
        slot: 'signoff',
      },
      {
        id: 'signoff-safety-net',
        title: 'Sign-off — with built-in safety-net catch-all',
        body: "I hope this helps. Please do get back in touch if things change, don't improve as expected, or if you're ever worried — or if you just feel something isn't right. Best wishes, Dr ***",
        trigger: 'signoffsn',
        keywords: "sign off safety net catch all closing something isn't right",
        category: 'sign-offs',
        audience: 'patient',
        leafletUrl: '',
        slot: 'signoff',
      },
      {
        id: 'signoff-thanks',
        title: 'Sign-off — thank you, feel better soon',
        body: 'Thank you for getting in touch, and I hope you feel better soon. Dr ***',
        trigger: 'signoffthanks',
        keywords: 'sign off thank you feel better closing',
        category: 'sign-offs',
        audience: 'patient',
        leafletUrl: '',
        slot: 'signoff',
      },
    ],
  });

  const api = { SHIPPED_PACK };
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  } else {
    global.PhrasesPresets = api;
  }
})(typeof window !== 'undefined' ? window : globalThis);
