// © 2026 Graysbrook Ltd. Proprietary — all rights reserved. See LICENSE.
// Medicus Suite — Sweep reception handout renderer.
//
// Reads the model written by sweep.js (buildHandout output) from the transient
// 'sweep.handout' key and renders the printable worklist. The key is removed
// from storage immediately after render (consume-on-read), so patient-identifiable
// data does not linger on disk on shared GP workstations. Acceptable trade-off:
// a manual page refresh (F5) after this point will show the empty state because
// the one-shot payload has been consumed. This is intentional — it is better than
// leaving patient data on disk. The Print button works on the already-rendered DOM.
//
// Everything rendered here is patient-identifiable — all values go through
// esc() and the page carries a confidentiality banner that also prints.

'use strict';

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function fmtTime(iso) {
  if (!iso) return '';
  const d = new Date(iso);
  if (isNaN(d.getTime())) return String(iso);
  const pad = (n) => String(n).padStart(2, '0');
  return `${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

function fmtDate(iso) {
  const d = iso ? new Date(iso) : new Date();
  if (isNaN(d.getTime())) return String(iso);
  return d.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
}

// "Who is this handout for?" label. Prefers the canonical `clinicians` array;
// falls back to the single-name `clinician` for older payloads.
//   0 selected → "All clinicians"
//   1          → "<name>'s patients"
//   ≥2         → "<name1>, <name2>… (N clinicians)"
function clinicianWhoFor(model) {
  const list = Array.isArray(model.clinicians)
    ? model.clinicians.filter(Boolean)
    : model.clinician
      ? [model.clinician]
      : [];
  if (list.length === 0) return 'All clinicians';
  if (list.length === 1) return `${list[0]}'s patients`;
  return `${list.join(', ')} (${list.length} clinicians)`;
}

function patientHtml(p, showClinician) {
  const time = p.time ? `<span class="patient-time">${esc(fmtTime(p.time))}</span>` : '';
  const clin = showClinician && p.clinician ? `<span class="patient-clin">${esc(p.clinician)}</span>` : '';
  const actions = (p.actions || [])
    .map(
      (a) => `
    <div class="action">
      <span class="box">&#9744;</span>
      <span><span class="what">${esc(a.action)}</span>${a.detail ? ` <span class="why">— ${esc(a.detail)}</span>` : ''}</span>
    </div>`
    )
    .join('');
  const hiddenNote = p.hasHiddenActionChips
    ? `<div class="hidden-note">Some alerts for this patient are hidden in the Sentinel panel — a clinician should review the record.</div>`
    : '';
  return `
    <div class="patient">
      <div class="patient-head">${time}<span class="patient-name">${esc(p.name)}</span>${clin}</div>
      ${actions}
      ${hiddenNote}
    </div>`;
}

async function render() {
  const content = document.getElementById('content');
  const r = await chrome.storage.local.get('sweep.handout');
  const model = r['sweep.handout'];

  if (!model || !Array.isArray(model.patients) || model.patients.length === 0) {
    content.innerHTML = `<div class="empty">No worklist found. Run a sweep in the side panel, then click "Print reception handout".</div>`;
    return;
  }

  const whoFor = clinicianWhoFor(model);
  const taskCount = model.patients.reduce((n, p) => n + (p.actions ? p.actions.length : 0), 0);

  // The clinic day the sweep was for (may be today or a future clinic) — kept
  // distinct from when the handout was generated, so a printout for a future
  // clinic states which day it covers.
  const clinicDay = model.clinicDate
    ? fmtDate(/^\d{4}-\d{2}-\d{2}$/.test(model.clinicDate) ? model.clinicDate + 'T12:00:00' : model.clinicDate)
    : fmtDate(model.generatedAt);

  content.innerHTML = `
    <h1>Pre-clinic sweep for ${esc(clinicDay)}</h1>
    <div class="meta">${esc(whoFor)} &middot; ${model.patients.length} patient${model.patients.length === 1 ? '' : 's'}, ${taskCount} task${taskCount === 1 ? '' : 's'} &middot; generated ${esc(new Date(model.generatedAt).toLocaleString('en-GB'))} &middot; Medicus Suite v${esc(model.suiteVersion || '')}</div>
    <div class="confidential">Confidential &mdash; patient identifiable. Do not leave unattended. Destroy after use.</div>
    ${model.patients.map((p) => patientHtml(p, !model.clinician)).join('')}
    <div class="footer">
      Tick each box as you complete it. If a patient declines or you are unsure about any item, flag it to the duty clinician rather than skipping it.<br>
      Generated by Medicus Suite from a point-in-time snapshot &mdash; a clinician must verify alerts against the source record. No item on this list is a clinical instruction; it is a booking/flagging worklist for reception.
    </div>`;

  // Consume-on-read: remove the transient key now that the DOM is rendered.
  // The Print button works on the already-rendered DOM; a page refresh will
  // show the empty state — that is intentional (privacy over convenience).
  await chrome.storage.local.remove('sweep.handout').catch(() => {});
}

document.getElementById('printBtn').addEventListener('click', () => window.print());
render();
